spring:
  datasource:
    url: jdbc:h2:mem:hermes
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

search:
  synonyms:
    seniority:
      especialista: senior
      coordenador: manager
    area:
      sre: devops
      platform: backend
    stacks:
      - elixir
      - rust
    locations:
      - chile
      - colombia
